#!/bin/sh

# Run Prettier against all files staged for commit
FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# Prettify all files except node_modules
echo "$FILES" | xargs ./node_modules/.bin/prettier --ignore-unknown --write

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

# Run unit tests prior to committing
yarn --cwd ./services/app-api test
yarn --cwd ./services/ui-src test
