export interface SPAi {
  id: string;
  state: string;
  name: string;
}

export const SPA: { [year: string]: SPAi[] } = {
  "2021": [
    {
      id: "19-0037",
      state: "CA",
      name: "California Health Home Program (HHP)",
    },
    { id: "20-0002", state: "CA", name: "California Behavioral Health Home" },
    {
      id: "15-014",
      state: "CT",
      name: "Serious and Persistent Mental Illness",
    },
    {
      id: "18-006",
      state: "DE",
      name: "Delaware Assertive Community Integration Support Team (ACIST) Health Home",
    },
    {
      id: "18-0006",
      state: "DC",
      name: "Chronic Care Management for Individuals with Serious and Persistent Mental Health Conditions",
    },
    { id: "18-0007", state: "DC", name: "Chronic Conditions" },
    { id: "20-0010", state: "IA", name: "Iowa Health Home Services" },
    {
      id: "20-0011",
      state: "IA",
      name: "Iowa Severe and Persistent Mental Illness Health Home ",
    },
    {
      id: "20-0004",
      state: "KS",
      name: "Health Home Serving Serious Mental Illness (SMI)",
    },
    {
      id: "20-0005",
      state: "KS",
      name: "Health Home Chronic Conditions - Asthma",
    },
    {
      id: "13-012",
      state: "ME",
      name: "Maine Stage A Health Home Targeting Individuals with Chronic Conditions",
    },
    { id: "18-0002", state: "ME", name: "Maine Behavioral Health Home" },
    {
      id: "18-0032",
      state: "ME",
      name: "Maine Health Home for Beneficiaries Receiving Medication Assisted Treatment for Opioid Addiction",
    },
    { id: "20-0006", state: "MD", name: "Maryland Health Home Services" },
    {
      id: "16-1500",
      state: "MI",
      name: "Chronic Care Model for Individuals with Serious and Persistent Mental Health Conditions",
    },
    { id: "15-2000", state: "MI", name: "Michigan Care Team" },
    { id: "18-1500", state: "MI", name: "Opioid Health Home" },
    { id: "19-0015", state: "MN", name: "Minnesota Behavioral Health Homes" },
    {
      id: "19-0020",
      state: "MO",
      name: "Community Mental Health Center Health Home",
    },
    { id: "19-0003", state: "MO", name: "Primary Care Clinic Health Home" },
    {
      id: "16-0001",
      state: "NJ",
      name: "New Jersey Behavioral Health Home (Adults)",
    },
    {
      id: "16-0002",
      state: "NJ",
      name: "New Jersey Behavioral Health Home (Children)",
    },
    { id: "18-0002", state: "NM", name: "CareLink New Mexico" },
    {
      id: "20-0054",
      state: "NY",
      name: "Health Home for High-Cost, High-Needs Enrollees ",
    },
    { id: "17-0025", state: "NY", name: "New York I/DD Health Home Services" },
    { id: "14-0012", state: "OK", name: "Oklahoma Health Home (Adults)" },
    { id: "14-0011", state: "OK", name: "Oklahoma Health Home (Children)" },
    {
      id: "18-009",
      state: "RI",
      name: "Comprehensive Evaluation, Diagnosis, Assessment, Referral, & Reevaluation (CEDARR) Family Centers Health Home",
    },
    {
      id: "18-006",
      state: "RI",
      name: "Community Mental Health Organizations Health Home",
    },
    {
      id: "16-006",
      state: "RI",
      name: "Rhode Island Opioid Treatment Program Health Home Services",
    },
    { id: "20-0008", state: "SD", name: "South Dakota Health Home" },
    {
      id: "16-004",
      state: "TN",
      name: "Tennessee Health Link Health Home Program ",
    },
    {
      id: "14-007",
      state: "VT",
      name: "Vermont Health Home for Beneficiaries Receiving Medication Assisted Treatment for Opioid Addiction ",
    },
    { id: "20-0031", state: "WA", name: "Washington Health Home Services" },
    {
      id: "16-0007",
      state: "WV",
      name: "West Virginia Health Home for Individuals with Bipolar Disorder at Risk for Hepatitis Type B and C",
    },
    {
      id: "16-0008",
      state: "WV",
      name: "West Virginia Health Home for Individuals with Chronic Conditions",
    },
    { id: "12-008", state: "WI", name: "Individuals with HIV/AIDS" },
  ],
  "2022": [
    {
      id: "19-0037",
      state: "CA",
      name: "California Health Home Program (HHP)",
    },
    { id: "20-0002", state: "CA", name: "California Behavioral Health Home" },
    {
      id: "15-014",
      state: "CT",
      name: "Serious and Persistent Mental Illness",
    },
    {
      id: "18-006",
      state: "DE",
      name: "Delaware Assertive Community Integration Support Team (ACIST) Health Home",
    },
    {
      id: "18-0006",
      state: "DC",
      name: "Chronic Care Management for Individuals with Serious and Persistent Mental Health Conditions",
    },
    { id: "18-0007", state: "DC", name: "Chronic Conditions" },
    { id: "20-0010", state: "IA", name: "Iowa Health Home Services" },
    {
      id: "20-0011",
      state: "IA",
      name: "Iowa Severe and Persistent Mental Illness Health Home ",
    },
    {
      id: "20-0004",
      state: "KS",
      name: "Health Home Serving Serious Mental Illness (SMI)",
    },
    {
      id: "20-0005",
      state: "KS",
      name: "Health Home Chronic Conditions - Asthma",
    },
    {
      id: "13-012",
      state: "ME",
      name: "Maine Stage A Health Home Targeting Individuals with Chronic Conditions",
    },
    { id: "18-0002", state: "ME", name: "Maine Behavioral Health Home" },
    {
      id: "18-0032",
      state: "ME",
      name: "Maine Health Home for Beneficiaries Receiving Medication Assisted Treatment for Opioid Addiction",
    },
    { id: "21-0005", state: "MD", name: "Maryland Health Home Services" },
    {
      id: "20-1500",
      state: "MI",
      name: "Chronic Care Model for Individuals with Serious and Persistent Mental Health Conditions",
    },
    { id: "15-2000", state: "MI", name: "Michigan Care Team" },
    { id: "20-1501", state: "MI", name: "Opioid Health Home" },
    { id: "19-0015", state: "MN", name: "Minnesota Behavioral Health Homes" },
    {
      id: "19-0020",
      state: "MO",
      name: "Community Mental Health Center Health Home",
    },
    { id: "19-0003", state: "MO", name: "Primary Care Clinic Health Home" },
    {
      id: "16-0001",
      state: "NJ",
      name: "New Jersey Behavioral Health Home (Adults)",
    },
    {
      id: "16-0002",
      state: "NJ",
      name: "New Jersey Behavioral Health Home (Children)",
    },
    { id: "18-0002", state: "NM", name: "CareLink New Mexico" },
    {
      id: "20-0054",
      state: "NY",
      name: "Health Home for High-Cost, High-Needs Enrollees ",
    },
    { id: "17-0025", state: "NY", name: "New York I/DD Health Home Services" },
    { id: "14-0012", state: "OK", name: "Oklahoma Health Home (Adults)" },
    { id: "14-0011", state: "OK", name: "Oklahoma Health Home (Children)" },
    {
      id: "18-009",
      state: "RI",
      name: "Comprehensive Evaluation, Diagnosis, Assessment, Referral, & Reevaluation (CEDARR) Family Centers Health Home",
    },
    {
      id: "18-006",
      state: "RI",
      name: "Community Mental Health Organizations Health Home",
    },
    {
      id: "16-006",
      state: "RI",
      name: "Rhode Island Opioid Treatment Program Health Home Services",
    },
    { id: "20-0008", state: "SD", name: "South Dakota Health Home" },
    {
      id: "16-004",
      state: "TN",
      name: "Tennessee Health Link Health Home Program ",
    },
    {
      id: "14-007",
      state: "VT",
      name: "Vermont Health Home for Beneficiaries Receiving Medication Assisted Treatment for Opioid Addiction ",
    },
    { id: "20-0031", state: "WA", name: "Washington Health Home Services" },
    {
      id: "16-0007",
      state: "WV",
      name: "West Virginia Health Home for Individuals with Bipolar Disorder at Risk for Hepatitis Type B and C",
    },
    {
      id: "16-0008",
      state: "WV",
      name: "West Virginia Health Home for Individuals with Chronic Conditions",
    },
    { id: "12-008", state: "WI", name: "Individuals with HIV/AIDS" },
    { id: "21-0012", state: "WI", name: "Substance Use Disorder Health Home" },
  ],
  "2023": [
    {
      id: "15-014",
      state: "CT",
      name: "Serious and Persistent Mental Illness",
    },
    {
      id: "18-0006",
      state: "DC",
      name: "Chronic Care Management for Individuals with Serious and Persistent Mental Health Conditions",
    },
    { id: "18-0007", state: "DC", name: "Chronic Conditions" },
    { id: "22-0003", state: "IA", name: "Iowa Health Home Services" },
    {
      id: "20-0011",
      state: "IA",
      name: "Iowa Severe and Persistent Mental Illness Health Home ",
    },
    {
      id: "20-0004",
      state: "KS",
      name: "Health Home Serving Serious Mental Illness (SMI)",
    },
    {
      id: "20-0005",
      state: "KS",
      name: "Health Home Chronic Conditions - Asthma",
    },
    {
      id: "13-012",
      state: "ME",
      name: "Maine Stage A Health Home Targeting Individuals with Chronic Conditions",
    },
    { id: "18-0002", state: "ME", name: "Maine Behavioral Health Home" },
    {
      id: "22-0018",
      state: "ME",
      name: "Maine Health Home for Beneficiaries Receiving Medication Assisted Treatment for Opioid Addiction",
    },
    { id: "21-0005", state: "MD", name: "Maryland Health Home Services" },
    {
      id: "20-1500",
      state: "MI",
      name: "Chronic Care Model for Individuals with Serious and Persistent Mental Health Conditions",
    },
    { id: "15-2000", state: "MI", name: "Michigan Care Team" },
    { id: "22-1501", state: "MI", name: "Opioid Health Home" },
    { id: "19-0015", state: "MN", name: "Minnesota Behavioral Health Homes" },
    {
      id: "19-0020",
      state: "MO",
      name: "Community Mental Health Center Health Home",
    },
    { id: "19-0003", state: "MO", name: "Primary Care Clinic Health Home" },
    {
      id: "16-0001",
      state: "NJ",
      name: "New Jersey Behavioral Health Home (Adults)",
    },
    {
      id: "16-0002",
      state: "NJ",
      name: "New Jersey Behavioral Health Home (Children)",
    },
    { id: "18-0002", state: "NM", name: "CareLink New Mexico" },
    {
      id: "21-0072",
      state: "NY",
      name: "Health Home for High-Cost, High-Needs Enrollees ",
    },
    { id: "22-0073", state: "NY", name: "New York I/DD Health Home Services" },
    {
      id: "18-009",
      state: "RI",
      name: "Comprehensive Evaluation, Diagnosis, Assessment, Referral, & Reevaluation (CEDARR) Family Centers Health Home",
    },
    {
      id: "18-006",
      state: "RI",
      name: "Community Mental Health Organizations Health Home",
    },
    {
      id: "21-0025",
      state: "RI",
      name: "Rhode Island Opioid Treatment Program Health Home Services",
    },
    { id: "20-0008", state: "SD", name: "South Dakota Health Home" },
    {
      id: "16-004",
      state: "TN",
      name: "Tennessee Health Link Health Home Program ",
    },
    {
      id: "14-007",
      state: "VT",
      name: "Vermont Health Home for Beneficiaries Receiving Medication Assisted Treatment for Opioid Addiction ",
    },
    { id: "20-0031", state: "WA", name: "Washington Health Home Services" },
    {
      id: "16-0007",
      state: "WV",
      name: "West Virginia Health Home for Individuals with Bipolar Disorder at Risk for Hepatitis Type B and C",
    },
    {
      id: "16-0008",
      state: "WV",
      name: "West Virginia Health Home for Individuals with Chronic Conditions",
    },
    { id: "12-008", state: "WI", name: "Individuals with HIV/AIDS" },
    { id: "21-0012", state: "WI", name: "Substance Use Disorder Health Home" },
  ],
  "2024": [
    {
      id: "15-014",
      state: "CT",
      name: "Serious and Persistent Mental Illness",
    },
    {
      id: "18-0006",
      state: "DC",
      name: "Chronic Care Management for Individuals with Serious and Persistent Mental Health Conditions",
    },
    { id: "18-0007", state: "DC", name: "Chronic Conditions" },
    { id: "22-0004", state: "IA", name: "Iowa Health Home Services" },
    {
      id: "20-0011",
      state: "IA",
      name: "Iowa Severe and Persistent Mental Illness Health Home ",
    },
    {
      id: "20-0004",
      state: "KS",
      name: "Health Home Serving Serious Mental Illness (SMI)",
    },
    {
      id: "20-0005",
      state: "KS",
      name: "Health Home Chronic Conditions - Asthma",
    },
    {
      id: "22-0033-CT",
      state: "ME",
      name: "Maine Stage A Health Home Targeting Individuals with Chronic Conditions",
    },
    { id: "23-0014-BHH", state: "ME", name: "Maine Behavioral Health Home" },
    {
      id: "22-0018",
      state: "ME",
      name: "Maine Health Home for Beneficiaries Receiving Medication Assisted Treatment for Opioid Addiction",
    },
    { id: "21-0005", state: "MD", name: "Maryland Health Home Services" },
    {
      id: "20-1500",
      state: "MI",
      name: "Chronic Care Model for Individuals with Serious and Persistent Mental Health Conditions",
    },
    { id: "15-2000", state: "MI", name: "Michigan Care Team" },
    { id: "23-1500", state: "MI", name: "Opioid Health Home" },
    { id: "22-0036", state: "MN", name: "Minnesota Behavioral Health Homes" },
    {
      id: "19-0020",
      state: "MO",
      name: "Community Mental Health Center Health Home",
    },
    { id: "19-0003", state: "MO", name: "Primary Care Clinic Health Home" },
    {
      id: "16-0001",
      state: "NJ",
      name: "New Jersey Behavioral Health Home (Adults)",
    },
    {
      id: "16-0002",
      state: "NJ",
      name: "New Jersey Behavioral Health Home (Children)",
    },
    { id: "18-0002", state: "NM", name: "CareLink New Mexico" },
    {
      id: "22-0088",
      state: "NY",
      name: "Health Home for High-Cost, High-Needs Enrollees ",
    },
    { id: "23-0062", state: "NY", name: "New York I/DD Health Home Services" },
    { id: "22-0024", state: "NC", name: "Tailored Care Management" },
    {
      id: "18-009",
      state: "RI",
      name: "Comprehensive Evaluation, Diagnosis, Assessment, Referral, & Reevaluation (CEDARR) Family Centers Health Home",
    },
    {
      id: "18-006",
      state: "RI",
      name: "Community Mental Health Organizations Health Home",
    },
    {
      id: "21-0025",
      state: "RI",
      name: "Rhode Island Opioid Treatment Program Health Home Services",
    },
    { id: "22-0009", state: "SD", name: "South Dakota Health Home" },
    {
      id: "16-004",
      state: "TN",
      name: "Tennessee Health Link Health Home Program ",
    },
    {
      id: "14-007",
      state: "VT",
      name: "Vermont Health Home for Beneficiaries Receiving Medication Assisted Treatment for Opioid Addiction ",
    },
    { id: "23-0027", state: "WA", name: "Washington Health Home Services" },
    {
      id: "16-0007",
      state: "WV",
      name: "West Virginia Health Home for Individuals with Bipolar Disorder at Risk for Hepatitis Type B and C",
    },
    {
      id: "16-0008",
      state: "WV",
      name: "West Virginia Health Home for Individuals with Chronic Conditions",
    },
    { id: "12-008", state: "WI", name: "Individuals with HIV/AIDS" },
    { id: "22-0013", state: "WI", name: "Substance Use Disorder Health Home" },
  ],
  "2025": [
    {
      id: "15-014",
      state: "CT",
      name: "Serious and Persistent Mental Illness",
    },
    {
      id: "18-0006",
      state: "DC",
      name: "Chronic Care Management for Individuals with Serious and Persistent Mental Health Conditions",
    },
    { id: "18-0007", state: "DC", name: "Chronic Conditions" },
    { id: "22-0004", state: "IA", name: "Iowa Health Home Services" },
    {
      id: "20-0011",
      state: "IA",
      name: "Iowa Severe and Persistent Mental Illness Health Home ",
    },
    {
      id: "20-0004",
      state: "KS",
      name: "Health Home Serving Serious Mental Illness (SMI)",
    },
    {
      id: "20-0005",
      state: "KS",
      name: "Health Home Chronic Conditions - Asthma",
    },
    {
      id: "22-0033-CT",
      state: "ME",
      name: "Maine Stage A Health Home Targeting Individuals with Chronic Conditions",
    },
    { id: "23-0014-BHH", state: "ME", name: "Maine Behavioral Health Home" },
    {
      id: "22-0018",
      state: "ME",
      name: "Maine Health Home for Beneficiaries Receiving Medication Assisted Treatment for Opioid Addiction",
    },
    { id: "21-0005", state: "MD", name: "Maryland Health Home Services" },
    {
      id: "20-1500",
      state: "MI",
      name: "Chronic Care Model for Individuals with Serious and Persistent Mental Health Conditions",
    },
    { id: "15-2000", state: "MI", name: "Michigan Care Team" },
    { id: "23-1500", state: "MI", name: "Opioid Health Home" },
    { id: "22-0036", state: "MN", name: "Minnesota Behavioral Health Homes" },
    {
      id: "19-0020",
      state: "MO",
      name: "Community Mental Health Center Health Home",
    },
    { id: "19-0003", state: "MO", name: "Primary Care Clinic Health Home" },
    {
      id: "16-0001",
      state: "NJ",
      name: "New Jersey Behavioral Health Home (Adults)",
    },
    {
      id: "16-0002",
      state: "NJ",
      name: "New Jersey Behavioral Health Home (Children)",
    },
    { id: "18-0002", state: "NM", name: "CareLink New Mexico" },
    {
      id: "22-0088",
      state: "NY",
      name: "Health Home for High-Cost, High-Needs Enrollees ",
    },
    { id: "23-0062", state: "NY", name: "New York I/DD Health Home Services" },
    { id: "22-0024", state: "NC", name: "Tailored Care Management" },
    {
      id: "18-009",
      state: "RI",
      name: "Comprehensive Evaluation, Diagnosis, Assessment, Referral, & Reevaluation (CEDARR) Family Centers Health Home",
    },
    {
      id: "18-006",
      state: "RI",
      name: "Community Mental Health Organizations Health Home",
    },
    {
      id: "21-0025",
      state: "RI",
      name: "Rhode Island Opioid Treatment Program Health Home Services",
    },
    { id: "22-0009", state: "SD", name: "South Dakota Health Home" },
    {
      id: "16-004",
      state: "TN",
      name: "Tennessee Health Link Health Home Program ",
    },
    {
      id: "14-007",
      state: "VT",
      name: "Vermont Health Home for Beneficiaries Receiving Medication Assisted Treatment for Opioid Addiction ",
    },
    { id: "23-0027", state: "WA", name: "Washington Health Home Services" },
    {
      id: "16-0007",
      state: "WV",
      name: "West Virginia Health Home for Individuals with Bipolar Disorder at Risk for Hepatitis Type B and C",
    },
    {
      id: "16-0008",
      state: "WV",
      name: "West Virginia Health Home for Individuals with Chronic Conditions",
    },
    { id: "12-008", state: "WI", name: "Individuals with HIV/AIDS" },
    { id: "22-0013", state: "WI", name: "Substance Use Disorder Health Home" },
  ],
};
