export const testingYear = "2024";

export const measureAbbrList2024 = {
  ADULT: ["PQI08-AD", "PQI15-AD", "SAA-AD", "SSD-AD"],
  CHILD: [
    "AAB-CH",
    "ADD-CH",
    "AMB-CH",
    "AMR-CH",
    "APM-CH",
    "APP-CH",
    "CCP-CH",
    "CCW-CH",
    "CDF-CH",
    "CHL-CH",
    "CIS-CH",
    "CPC-CH",
    "DEV-CH",
    "FUA-CH",
    "FUH-CH",
    "FUM-CH",
    "IMA-CH",
    "LBW-CH", // complete on creation
    "LRCD-CH", // complete on creation
    "LSC-CH",
    "OEV-CH",
    "PPC2-CH",
    "SFM-CH",
    "TFL-CH",
    "W30-CH",
    "WCC-CH",
    "WCV-CH",
  ],
  HEALTH_HOME: [
    "AIF-HH",
    "AMB-HH",
    "CBP-HH",
    "CDF-HH",
    "COL-HH",
    "FUA-HH",
    "FUH-HH",
    "FUM-HH",
    "IET-HH",
    "IU-HH",
    "OUD-HH",
    "PCR-HH",
    "PQI92-HH",
  ],
};
