const emailForCognito = "//input[@name='email']";
const passwordForCognito = "//input[@name='password']";

describe("OY2 8977 Measure 15 MSC-AD", () => {
  beforeEach(() => {
    cy.visit("/");
    cy.login();
    cy.goToAdultMeasures();
    cy.goToMeasure("MSC-AD");
  });

  it("User click on No option for the first question and fill out the form with No option", () => {
    cy.get(".css-itvw0n").should(
      "have.text",
      "For technical questions regarding use of this application, please reach out to MDCT_Help@cms.hhs.gov. For content-related questions about measure specifications, or what information to enter in each field, please reach out to MACQualityTA@cms.hhs.gov."
    );
    cy.get("[data-cy=DidReport1]").click({ force: true });
    cy.get(
      "[data-cy=WhyAreYouNotReporting0] > .chakra-checkbox__control"
    ).click({ force: true });

    cy.get(
      "[data-cy=WhyAreYouNotReporting1] > .chakra-checkbox__control"
    ).click();
  });

  /* ==== Test Created with Cypress Studio ==== */
  it.skip("Click on Yes option from first question", function () {
    cy.get("[data-cy=DidReport0]").click({ force: true }); // clicking yes
    cy.get("[data-cy=DataStatus0]").click({ force: true });
    cy.get("[data-cy=MeasurementSpecification0]").click({ force: true });
    cy.xpath("(//span[@class='chakra-radio__control css-gzpnyx'])[7]").click();
    cy.get("[data-cy=MeasurementSpecification-HEDISVersion]").select(
      "HEDIS MY 2020 (FFY 2021 Core Set Reporting)"
    );
    cy.xpath("(//input[@label='Month'])[1]").clear();
    cy.xpath("(//input[@label='Month'])[1]").type("10");
    cy.xpath("(//input[@label='Year'])[1]").clear();
    cy.xpath("(//input[@label='Year'])[1]").type("2019");
    cy.xpath("(//input[@label='Month'])[2]").clear();
    cy.xpath("(//input[@label='Month'])[2]").type("10");
    cy.xpath("(//input[@label='Year'])[2]").clear();
    cy.xpath("(//input[@label='Year'])[2]").type("2021");
    cy.get(
      "[data-cy=DefinitionOfDenominator0] > .chakra-checkbox__control"
    ).click();
    cy.get("[data-cy=DefinitionOfDenominator1]").click();
    cy.get(
      "[data-cy=DefinitionOfDenominator2] > .chakra-checkbox__control"
    ).click();
    cy.get(
      "[data-cy=DefinitionOfDenominator3] > .chakra-checkbox__control"
    ).click();
    cy.get("[data-cy=DefinitionOfDenominator-Other]").click();
    cy.get("[data-cy=ChangeInPopulationExplanation]").click();
    cy.get("[data-cy=DenominatorDefineTotalTechSpec0]").click();
    cy.get(
      "[data-cy=DeliverySysRepresentationDenominator0] > .chakra-checkbox__control"
    ).click();
    cy.get("[data-cy=DeliverySys-FeeForService0]").click();
    cy.get(
      "[data-cy=DeliverySysRepresentationDenominator1] > .chakra-checkbox__control"
    ).click();
    cy.get("[data-cy=DeliverySys-PrimaryCareManagement0]").click();
    cy.get(
      "[data-cy=DeliverySysRepresentationDenominator2] > .chakra-checkbox__control"
    ).click();
    cy.get("[data-cy=DeliverySys-MCO_PIHP-NumberOfPlans]").clear();
    cy.get("[data-cy=DeliverySys-MCO_PIHP-NumberOfPlans]").type("20");
    cy.get("[data-cy=DeliverySys-MCO_PIHP0]").click();
    cy.get(
      "[data-cy=DeliverySysRepresentationDenominator3] > .chakra-checkbox__control"
    ).click();
    cy.get("[data-cy=DeliverySys-IntegratedCareModel0]").click();
    cy.get(
      "[data-cy=DeliverySysRepresentationDenominator4] > .chakra-checkbox__control"
    ).click();
    cy.get("[data-cy=DeliverySys-Other]").click();
    cy.get("[data-cy=DeliverySys-Other-Percent]").clear();
    cy.get("[data-cy=DeliverySys-Other-Percent]").type("10");
    cy.get("[data-cy=DeliverySys-Other-NumberOfHealthPlans]").clear();
    cy.get("[data-cy=DeliverySys-Other-NumberOfHealthPlans]").type("20");

    cy.get("[data-cy=PerformanceMeasure-Explanation]").click();
    /* ==== Performance Measure and Deviations from Measure Specifications ==== */
    cy.get(
      '[data-cy="PerformanceMeasure-AgeRates-AdvisingUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="PerformanceMeasure-AgeRates-AdvisingUsers.0.numerator"]'
    ).type("2");
    cy.get(
      '[data-cy="PerformanceMeasure-AgeRates-AdvisingUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="PerformanceMeasure-AgeRates-AdvisingUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="PerformanceMeasure-AgeRates-AdvisingUsers.1.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="PerformanceMeasure-AgeRates-AdvisingUsers.1.numerator"]'
    ).type("2");
    cy.get(
      '[data-cy="PerformanceMeasure-AgeRates-AdvisingUsers.1.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="PerformanceMeasure-AgeRates-AdvisingUsers.1.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="PerformanceMeasure-AgeRates-AdvisingUsers.1.rate"]'
    ).should("have.value", "20.0");
    cy.get(
      '[data-cy="PerformanceMeasure-AgeRates-DiscussingMedications.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="PerformanceMeasure-AgeRates-DiscussingMedications.0.numerator"]'
    ).type("4");
    cy.get(
      '[data-cy="PerformanceMeasure-AgeRates-DiscussingMedications.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="PerformanceMeasure-AgeRates-DiscussingMedications.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="PerformanceMeasure-AgeRates-DiscussingMedications.1.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="PerformanceMeasure-AgeRates-DiscussingMedications.1.numerator"]'
    ).type("7");
    cy.get(
      '[data-cy="PerformanceMeasure-AgeRates-DiscussingMedications.1.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="PerformanceMeasure-AgeRates-DiscussingMedications.1.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="PerformanceMeasure-AgeRates-DiscussingStrategies.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="PerformanceMeasure-AgeRates-DiscussingStrategies.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="PerformanceMeasure-AgeRates-DiscussingStrategies.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="PerformanceMeasure-AgeRates-DiscussingStrategies.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="PerformanceMeasure-AgeRates-DiscussingStrategies.1.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="PerformanceMeasure-AgeRates-DiscussingStrategies.1.numerator"]'
    ).type("4");
    cy.get(
      '[data-cy="PerformanceMeasure-AgeRates-DiscussingStrategies.1.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="PerformanceMeasure-AgeRates-DiscussingStrategies.1.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="PerformanceMeasure-AgeRates-PercentageUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="PerformanceMeasure-AgeRates-PercentageUsers.0.numerator"]'
    ).type("4");
    cy.get(
      '[data-cy="PerformanceMeasure-AgeRates-PercentageUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="PerformanceMeasure-AgeRates-PercentageUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="PerformanceMeasure-AgeRates-PercentageUsers.1.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="PerformanceMeasure-AgeRates-PercentageUsers.1.numerator"]'
    ).type("4");
    cy.get(
      '[data-cy="PerformanceMeasure-AgeRates-PercentageUsers.1.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="PerformanceMeasure-AgeRates-PercentageUsers.1.denominator"]'
    ).type("10");
    cy.get(
      "#DidCalculationsDeviate_radiogroup > .chakra-stack > :nth-child(1) > .chakra-radio"
    ).click();
    cy.get("[data-cy=DeviationOptions0] > .chakra-checkbox__control").click();
    cy.get(
      "[data-cy=DeviationOptions-AdvisingUsersToQuit-AgeRange0] > .chakra-checkbox__control"
    ).click();
    cy.get(
      '[data-cy="DeviationFields-AdvisingUsersToQuit.0.options0"] > .chakra-checkbox__control'
    ).click();
    cy.get(
      '[data-cy="DeviationFields-AdvisingUsersToQuit.0.numerator"]'
    ).click();
    cy.get(
      '[data-cy="DeviationFields-AdvisingUsersToQuit.0.options1"] > .chakra-checkbox__control'
    ).click();
    cy.get(
      '[data-cy="DeviationFields-AdvisingUsersToQuit.0.denominator"]'
    ).click();
    cy.get(
      '[data-cy="DeviationFields-AdvisingUsersToQuit.0.options2"] > .chakra-checkbox__control'
    ).click();
    cy.get('[data-cy="DeviationFields-AdvisingUsersToQuit.0.other"]').click();
    cy.get(
      "[data-cy=DeviationOptions-AdvisingUsersToQuit-AgeRange1] > .chakra-checkbox__control"
    ).click();
    cy.get(
      '[data-cy="DeviationFields-AdvisingUsersToQuit.1.options0"] > .chakra-checkbox__control'
    ).click();
    cy.get(
      '[data-cy="DeviationFields-AdvisingUsersToQuit.1.numerator"]'
    ).click();
    cy.get(
      '[data-cy="DeviationFields-AdvisingUsersToQuit.1.options1"] > .chakra-checkbox__control'
    ).click();
    cy.get(
      '[data-cy="DeviationFields-AdvisingUsersToQuit.1.denominator"]'
    ).click();
    cy.get(
      '[data-cy="DeviationFields-AdvisingUsersToQuit.1.options2"] > .chakra-checkbox__control'
    ).click();
    cy.get('[data-cy="DeviationFields-AdvisingUsersToQuit.1.other"]').click();
    cy.get("[data-cy=DeviationOptions1] > .chakra-checkbox__control").click();
    cy.get(
      "[data-cy=DeviationOptions-DiscussingCessationMedications-AgeRange0] > .chakra-checkbox__control"
    ).click();
    cy.get(
      '[data-cy="DeviationFields-DiscussingCessationMedications.0.options0"] > .chakra-checkbox__control'
    ).click();
    cy.get(
      '[data-cy="DeviationFields-DiscussingCessationMedications.0.numerator"]'
    ).click();
    cy.get(
      '[data-cy="DeviationFields-DiscussingCessationMedications.0.options1"] > .chakra-checkbox__control'
    ).click();
    cy.get(
      '[data-cy="DeviationFields-DiscussingCessationMedications.0.denominator"]'
    ).click();
    cy.get(
      '[data-cy="DeviationFields-DiscussingCessationMedications.0.options2"] > .chakra-checkbox__control'
    ).click();
    cy.get(
      '[data-cy="DeviationFields-DiscussingCessationMedications.0.other"]'
    ).click();
    cy.get(
      "[data-cy=DeviationOptions-DiscussingCessationMedications-AgeRange1] > .chakra-checkbox__control"
    ).click();
    cy.get(
      '[data-cy="DeviationFields-DiscussingCessationMedications.1.options0"] > .chakra-checkbox__control'
    ).click();
    cy.get(
      '[data-cy="DeviationFields-DiscussingCessationMedications.1.numerator"]'
    ).click();
    cy.get(
      '[data-cy="DeviationFields-DiscussingCessationMedications.1.options1"] > .chakra-checkbox__control'
    ).click();
    cy.get(
      '[data-cy="DeviationFields-DiscussingCessationMedications.1.denominator"]'
    ).click();
    cy.get(
      '[data-cy="DeviationFields-DiscussingCessationMedications.1.options2"] > .chakra-checkbox__control'
    ).click();
    cy.get(
      '[data-cy="DeviationFields-DiscussingCessationMedications.1.other"]'
    ).click();
    cy.get("[data-cy=DeviationOptions2]").click();
    cy.get(
      "[data-cy=DeviationOptions-DiscussingCessationStrategies-AgeRange0] > .chakra-checkbox__control"
    ).click();
    cy.get(
      '[data-cy="DeviationFields-DiscussingCessationStrategies.0.options0"] > .chakra-checkbox__control'
    ).click();
    cy.get(
      '[data-cy="DeviationFields-DiscussingCessationStrategies.0.numerator"]'
    ).click();
    cy.get(
      '[data-cy="DeviationFields-DiscussingCessationStrategies.0.options1"] > .chakra-checkbox__control'
    ).click();
    cy.get(
      '[data-cy="DeviationFields-DiscussingCessationStrategies.0.denominator"]'
    ).click();
    cy.get(
      '[data-cy="DeviationFields-DiscussingCessationStrategies.0.options2"] > .chakra-checkbox__control'
    ).click();
    cy.get(
      '[data-cy="DeviationFields-DiscussingCessationStrategies.0.other"]'
    ).click();
    cy.get(
      "[data-cy=DeviationOptions-DiscussingCessationStrategies-AgeRange1]"
    ).click();
    cy.get(
      '[data-cy="DeviationFields-DiscussingCessationStrategies.1.options0"] > .chakra-checkbox__control'
    ).click();
    cy.get(
      '[data-cy="DeviationFields-DiscussingCessationStrategies.1.numerator"]'
    ).click();
    cy.get(
      '[data-cy="DeviationFields-DiscussingCessationStrategies.1.options1"] > .chakra-checkbox__control'
    ).click();
    cy.get(
      '[data-cy="DeviationFields-DiscussingCessationStrategies.1.denominator"]'
    ).click();
    cy.get(
      '[data-cy="DeviationFields-DiscussingCessationStrategies.1.options2"]'
    ).click();
    cy.get(
      '[data-cy="DeviationFields-DiscussingCessationStrategies.1.other"]'
    ).click();
    cy.get("[data-cy=DeviationOptions3] > .chakra-checkbox__control").click();
    cy.get(
      "[data-cy=DeviationOptions-PercentageOfUsers-AgeRange0] > .chakra-checkbox__control"
    ).click();
    cy.get(
      '[data-cy="DeviationFields-PercentageOfUsers.0.options0"] > .chakra-checkbox__control'
    ).click();
    cy.get('[data-cy="DeviationFields-PercentageOfUsers.0.numerator"]').click();
    cy.get(
      '[data-cy="DeviationFields-PercentageOfUsers.0.options1"] > .chakra-checkbox__control'
    ).click();
    cy.get(
      '[data-cy="DeviationFields-PercentageOfUsers.0.denominator"]'
    ).click();
    cy.get(
      '[data-cy="DeviationFields-PercentageOfUsers.0.options2"] > .chakra-checkbox__control'
    ).click();

    cy.get('[data-cy="DeviationFields-PercentageOfUsers.0.other"]').click();
    cy.get("[data-cy=DeviationOptions-PercentageOfUsers-AgeRange1]").click();
    cy.get(
      '[data-cy="DeviationFields-PercentageOfUsers.1.options0"] > .chakra-checkbox__control'
    ).click();
    cy.get('[data-cy="DeviationFields-PercentageOfUsers.1.numerator"]').click();
    cy.get(
      '[data-cy="DeviationFields-PercentageOfUsers.1.options1"] > .chakra-checkbox__control'
    ).click();
    cy.get(
      '[data-cy="DeviationFields-PercentageOfUsers.1.denominator"]'
    ).click();
    cy.get(
      '[data-cy="DeviationFields-PercentageOfUsers.1.options2"] > .chakra-checkbox__control'
    ).click();
    cy.get('[data-cy="DeviationFields-PercentageOfUsers.1.other"]').click();
    cy.get("[data-cy=CombinedRates0]").click();
    cy.get("[data-cy=CombinedRates-CombinedRates0]").click();
    cy.get(
      "#CombinedRates-CombinedRates_radiogroup > .chakra-stack > :nth-child(2) > .chakra-radio"
    ).click();
    cy.get("[data-cy=CombinedRates-CombinedRates2]").click();
    cy.get("[data-cy=CombinedRates-CombinedRates-Other-Explanation]").click();
    cy.get("[data-cy=CategoriesReported0] > .chakra-checkbox__control").click();

    cy.get(
      "[data-cy=NonHispanicRacialCategories0] > .chakra-checkbox__control"
    ).click();
    cy.get(
      '[data-cy="NHRC-WhiteRates.ageData0"] > .chakra-checkbox__control'
    ).click();
    cy.get(
      '[data-cy="NHRC-WhiteRates.subRates.0.advisingUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-WhiteRates.subRates.0.advisingUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="NHRC-WhiteRates.subRates.0.advisingUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-WhiteRates.subRates.0.advisingUsers.0.denominator"]'
    ).type("10");
    cy.get(
      ".css-zhlq69 > :nth-child(3) > .chakra-stack > :nth-child(1)"
    ).click();
    cy.get(
      '[data-cy="NHRC-WhiteRates.subRates.0.discussingMedications.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-WhiteRates.subRates.0.discussingMedications.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="NHRC-WhiteRates.subRates.0.discussingMedications.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-WhiteRates.subRates.0.discussingMedications.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="NHRC-WhiteRates.subRates.0.discussingStrategies.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-WhiteRates.subRates.0.discussingStrategies.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="NHRC-WhiteRates.subRates.0.discussingStrategies.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-WhiteRates.subRates.0.discussingStrategies.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="NHRC-WhiteRates.subRates.0.percentageUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-WhiteRates.subRates.0.percentageUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="NHRC-WhiteRates.subRates.0.percentageUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-WhiteRates.subRates.0.percentageUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="NHRC-WhiteRates.ageData1"] > .chakra-checkbox__control'
    ).click();
    cy.get(
      '[data-cy="NHRC-WhiteRates.subRates.1.advisingUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-WhiteRates.subRates.1.advisingUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="NHRC-WhiteRates.subRates.1.advisingUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-WhiteRates.subRates.1.advisingUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="NHRC-WhiteRates.subRates.1.discussingMedications.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-WhiteRates.subRates.1.discussingMedications.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="NHRC-WhiteRates.subRates.1.discussingMedications.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-WhiteRates.subRates.1.discussingMedications.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="NHRC-WhiteRates.subRates.1.discussingStrategies.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-WhiteRates.subRates.1.discussingStrategies.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="NHRC-WhiteRates.subRates.1.discussingStrategies.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-WhiteRates.subRates.1.discussingStrategies.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="NHRC-WhiteRates.subRates.1.percentageUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-WhiteRates.subRates.1.percentageUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="NHRC-WhiteRates.subRates.1.percentageUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-WhiteRates.subRates.1.percentageUsers.0.denominator"]'
    ).type("10");
    cy.get(
      "[data-cy=NonHispanicRacialCategories1] > .chakra-checkbox__control"
    ).click();
    cy.get('[data-cy="NHRC-BlackOrAfricanAmericanRates.ageData0"]').click();
    cy.get(
      '[data-cy="NHRC-BlackOrAfricanAmericanRates.subRates.0.advisingUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-BlackOrAfricanAmericanRates.subRates.0.advisingUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="NHRC-BlackOrAfricanAmericanRates.subRates.0.advisingUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-BlackOrAfricanAmericanRates.subRates.0.advisingUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="NHRC-BlackOrAfricanAmericanRates.subRates.0.discussingMedications.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-BlackOrAfricanAmericanRates.subRates.0.discussingMedications.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="NHRC-BlackOrAfricanAmericanRates.subRates.0.discussingMedications.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-BlackOrAfricanAmericanRates.subRates.0.discussingMedications.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="NHRC-BlackOrAfricanAmericanRates.subRates.0.discussingStrategies.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-BlackOrAfricanAmericanRates.subRates.0.discussingStrategies.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="NHRC-BlackOrAfricanAmericanRates.subRates.0.discussingStrategies.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-BlackOrAfricanAmericanRates.subRates.0.discussingStrategies.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="NHRC-BlackOrAfricanAmericanRates.subRates.0.percentageUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-BlackOrAfricanAmericanRates.subRates.0.percentageUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="NHRC-BlackOrAfricanAmericanRates.subRates.0.percentageUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-BlackOrAfricanAmericanRates.subRates.0.percentageUsers.0.denominator"]'
    ).type("10");
    cy.get('[data-cy="NHRC-BlackOrAfricanAmericanRates.ageData1"]').click();
    cy.get(
      '[data-cy="NHRC-BlackOrAfricanAmericanRates.subRates.1.advisingUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-BlackOrAfricanAmericanRates.subRates.1.advisingUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="NHRC-BlackOrAfricanAmericanRates.subRates.1.advisingUsers.0.denominator"]'
    ).click();
    cy.get(
      '[data-cy="NHRC-BlackOrAfricanAmericanRates.subRates.1.advisingUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-BlackOrAfricanAmericanRates.subRates.1.advisingUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="NHRC-BlackOrAfricanAmericanRates.subRates.1.advisingUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-BlackOrAfricanAmericanRates.subRates.1.advisingUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="NHRC-BlackOrAfricanAmericanRates.subRates.1.discussingMedications.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-BlackOrAfricanAmericanRates.subRates.1.discussingMedications.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="NHRC-BlackOrAfricanAmericanRates.subRates.1.discussingMedications.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-BlackOrAfricanAmericanRates.subRates.1.discussingMedications.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="NHRC-BlackOrAfricanAmericanRates.subRates.1.discussingStrategies.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-BlackOrAfricanAmericanRates.subRates.1.discussingStrategies.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="NHRC-BlackOrAfricanAmericanRates.subRates.1.discussingStrategies.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-BlackOrAfricanAmericanRates.subRates.1.discussingStrategies.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="NHRC-BlackOrAfricanAmericanRates.subRates.1.percentageUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-BlackOrAfricanAmericanRates.subRates.1.percentageUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="NHRC-BlackOrAfricanAmericanRates.subRates.1.percentageUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-BlackOrAfricanAmericanRates.subRates.1.percentageUsers.0.denominator"]'
    ).type("10");
    cy.get(
      "[data-cy=NonHispanicRacialCategories2] > .chakra-checkbox__control"
    ).click();
    cy.get(
      '[data-cy="NHRC-AmericanIndianOrAlaskaNativeRates.ageData0"] > .chakra-checkbox__control'
    ).click();
    cy.get(
      '[data-cy="NHRC-AmericanIndianOrAlaskaNativeRates.subRates.0.advisingUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-AmericanIndianOrAlaskaNativeRates.subRates.0.advisingUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="NHRC-AmericanIndianOrAlaskaNativeRates.subRates.0.advisingUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-AmericanIndianOrAlaskaNativeRates.subRates.0.advisingUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="NHRC-AmericanIndianOrAlaskaNativeRates.subRates.0.discussingMedications.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-AmericanIndianOrAlaskaNativeRates.subRates.0.discussingMedications.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="NHRC-AmericanIndianOrAlaskaNativeRates.subRates.0.discussingMedications.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-AmericanIndianOrAlaskaNativeRates.subRates.0.discussingMedications.0.denominator"]'
    ).type("10");
    cy.get(
      ":nth-child(3) > :nth-child(2) > :nth-child(1) > .css-0 > :nth-child(1) > .css-n21gh5 > :nth-child(1) > .chakra-collapse > .css-zhlq69"
    ).click();
    cy.get(
      '[data-cy="NHRC-AmericanIndianOrAlaskaNativeRates.subRates.0.discussingStrategies.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-AmericanIndianOrAlaskaNativeRates.subRates.0.discussingStrategies.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="NHRC-AmericanIndianOrAlaskaNativeRates.subRates.0.discussingStrategies.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-AmericanIndianOrAlaskaNativeRates.subRates.0.discussingStrategies.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="NHRC-AmericanIndianOrAlaskaNativeRates.subRates.0.percentageUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-AmericanIndianOrAlaskaNativeRates.subRates.0.percentageUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="NHRC-AmericanIndianOrAlaskaNativeRates.subRates.0.percentageUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-AmericanIndianOrAlaskaNativeRates.subRates.0.percentageUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="NHRC-AmericanIndianOrAlaskaNativeRates.ageData1"]'
    ).click();
    cy.get(
      '[data-cy="NHRC-AmericanIndianOrAlaskaNativeRates.subRates.1.advisingUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-AmericanIndianOrAlaskaNativeRates.subRates.1.advisingUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="NHRC-AmericanIndianOrAlaskaNativeRates.subRates.1.advisingUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-AmericanIndianOrAlaskaNativeRates.subRates.1.advisingUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="NHRC-AmericanIndianOrAlaskaNativeRates.subRates.1.discussingMedications.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-AmericanIndianOrAlaskaNativeRates.subRates.1.discussingMedications.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="NHRC-AmericanIndianOrAlaskaNativeRates.subRates.1.discussingMedications.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-AmericanIndianOrAlaskaNativeRates.subRates.1.discussingMedications.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="NHRC-AmericanIndianOrAlaskaNativeRates.subRates.1.discussingStrategies.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-AmericanIndianOrAlaskaNativeRates.subRates.1.discussingStrategies.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="NHRC-AmericanIndianOrAlaskaNativeRates.subRates.1.discussingStrategies.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-AmericanIndianOrAlaskaNativeRates.subRates.1.discussingStrategies.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="NHRC-AmericanIndianOrAlaskaNativeRates.subRates.1.percentageUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-AmericanIndianOrAlaskaNativeRates.subRates.1.percentageUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="NHRC-AmericanIndianOrAlaskaNativeRates.subRates.1.percentageUsers.0.denominator"]'
    ).click();
    cy.get(
      '[data-cy="NHRC-AmericanIndianOrAlaskaNativeRates.subRates.1.percentageUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-AmericanIndianOrAlaskaNativeRates.subRates.1.percentageUsers.0.denominator"]'
    ).type("10");
    cy.get(
      "[data-cy=NonHispanicRacialCategories3] > .chakra-checkbox__control"
    ).click();
    cy.get("[data-cy=AsianIndependentReporting0]").click();
    cy.get(
      '[data-cy="NHRC-AggregateAsianRates.ageData0"] > .chakra-checkbox__control'
    ).click();
    cy.get(
      '[data-cy="NHRC-AggregateAsianRates.subRates.0.advisingUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-AggregateAsianRates.subRates.0.advisingUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="NHRC-AggregateAsianRates.subRates.0.advisingUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-AggregateAsianRates.subRates.0.advisingUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="NHRC-AggregateAsianRates.subRates.0.discussingMedications.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-AggregateAsianRates.subRates.0.discussingMedications.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="NHRC-AggregateAsianRates.subRates.0.discussingMedications.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-AggregateAsianRates.subRates.0.discussingMedications.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="NHRC-AggregateAsianRates.subRates.0.discussingStrategies.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-AggregateAsianRates.subRates.0.discussingStrategies.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="NHRC-AggregateAsianRates.subRates.0.discussingStrategies.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-AggregateAsianRates.subRates.0.discussingStrategies.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="NHRC-AggregateAsianRates.subRates.0.percentageUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-AggregateAsianRates.subRates.0.percentageUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="NHRC-AggregateAsianRates.subRates.0.percentageUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-AggregateAsianRates.subRates.0.percentageUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="NHRC-AggregateAsianRates.ageData1"] > .chakra-checkbox__control'
    ).click();
    cy.get(
      '[data-cy="NHRC-AggregateAsianRates.subRates.1.advisingUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-AggregateAsianRates.subRates.1.advisingUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="NHRC-AggregateAsianRates.subRates.1.advisingUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-AggregateAsianRates.subRates.1.advisingUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="NHRC-AggregateAsianRates.subRates.1.discussingMedications.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-AggregateAsianRates.subRates.1.discussingMedications.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="NHRC-AggregateAsianRates.subRates.1.discussingMedications.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-AggregateAsianRates.subRates.1.discussingMedications.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="NHRC-AggregateAsianRates.subRates.1.discussingStrategies.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-AggregateAsianRates.subRates.1.discussingStrategies.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="NHRC-AggregateAsianRates.subRates.1.discussingStrategies.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-AggregateAsianRates.subRates.1.discussingStrategies.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="NHRC-AggregateAsianRates.subRates.1.percentageUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-AggregateAsianRates.subRates.1.percentageUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="NHRC-AggregateAsianRates.subRates.1.percentageUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-AggregateAsianRates.subRates.1.percentageUsers.0.denominator"]'
    ).type("10");
    cy.get(
      "[data-cy=NonHispanicRacialCategories4] > .chakra-checkbox__control"
    ).click();
    cy.get("[data-cy=NativeHawaiianIndependentReporting0]").click();
    cy.get(
      '[data-cy="NHRC-AggregateHawaiianOrPacificIslanderRates.ageData0"]'
    ).click();
    cy.get(
      '[data-cy="NHRC-AggregateHawaiianOrPacificIslanderRates.subRates.0.advisingUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-AggregateHawaiianOrPacificIslanderRates.subRates.0.advisingUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="NHRC-AggregateHawaiianOrPacificIslanderRates.subRates.0.advisingUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-AggregateHawaiianOrPacificIslanderRates.subRates.0.advisingUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="NHRC-AggregateHawaiianOrPacificIslanderRates.subRates.0.discussingMedications.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-AggregateHawaiianOrPacificIslanderRates.subRates.0.discussingMedications.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="NHRC-AggregateHawaiianOrPacificIslanderRates.subRates.0.discussingMedications.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-AggregateHawaiianOrPacificIslanderRates.subRates.0.discussingMedications.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="NHRC-AggregateHawaiianOrPacificIslanderRates.subRates.0.discussingStrategies.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-AggregateHawaiianOrPacificIslanderRates.subRates.0.discussingStrategies.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="NHRC-AggregateHawaiianOrPacificIslanderRates.subRates.0.discussingStrategies.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-AggregateHawaiianOrPacificIslanderRates.subRates.0.discussingStrategies.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="NHRC-AggregateHawaiianOrPacificIslanderRates.subRates.0.percentageUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-AggregateHawaiianOrPacificIslanderRates.subRates.0.percentageUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="NHRC-AggregateHawaiianOrPacificIslanderRates.subRates.0.percentageUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-AggregateHawaiianOrPacificIslanderRates.subRates.0.percentageUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="NHRC-AggregateHawaiianOrPacificIslanderRates.ageData1"] > .chakra-checkbox__control'
    ).click();
    cy.get(
      '[data-cy="NHRC-AggregateHawaiianOrPacificIslanderRates.subRates.1.advisingUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-AggregateHawaiianOrPacificIslanderRates.subRates.1.advisingUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="NHRC-AggregateHawaiianOrPacificIslanderRates.subRates.1.advisingUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-AggregateHawaiianOrPacificIslanderRates.subRates.1.advisingUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="NHRC-AggregateHawaiianOrPacificIslanderRates.subRates.1.discussingMedications.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-AggregateHawaiianOrPacificIslanderRates.subRates.1.discussingMedications.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="NHRC-AggregateHawaiianOrPacificIslanderRates.subRates.1.discussingMedications.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-AggregateHawaiianOrPacificIslanderRates.subRates.1.discussingMedications.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="NHRC-AggregateHawaiianOrPacificIslanderRates.subRates.1.discussingStrategies.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-AggregateHawaiianOrPacificIslanderRates.subRates.1.discussingStrategies.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="NHRC-AggregateHawaiianOrPacificIslanderRates.subRates.1.discussingStrategies.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-AggregateHawaiianOrPacificIslanderRates.subRates.1.discussingStrategies.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="NHRC-AggregateHawaiianOrPacificIslanderRates.subRates.1.percentageUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-AggregateHawaiianOrPacificIslanderRates.subRates.1.percentageUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="NHRC-AggregateHawaiianOrPacificIslanderRates.subRates.1.percentageUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="NHRC-AggregateHawaiianOrPacificIslanderRates.subRates.1.percentageUsers.0.denominator"]'
    ).type("10");
    cy.get(
      "[data-cy=NonHispanicRacialCategories5] > .chakra-checkbox__control"
    ).click();
    cy.get(
      '[data-cy="AddtnlNonHispanicRaceRates.0.ageData0"] > .chakra-checkbox__control'
    ).click();
    cy.get(
      '[data-cy="AddtnlNonHispanicRaceRates.0.subRates.0.advisingUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="AddtnlNonHispanicRaceRates.0.subRates.0.advisingUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="AddtnlNonHispanicRaceRates.0.subRates.0.advisingUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="AddtnlNonHispanicRaceRates.0.subRates.0.advisingUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="AddtnlNonHispanicRaceRates.0.subRates.0.discussingMedications.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="AddtnlNonHispanicRaceRates.0.subRates.0.discussingMedications.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="AddtnlNonHispanicRaceRates.0.subRates.0.discussingMedications.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="AddtnlNonHispanicRaceRates.0.subRates.0.discussingMedications.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="AddtnlNonHispanicRaceRates.0.subRates.0.discussingStrategies.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="AddtnlNonHispanicRaceRates.0.subRates.0.discussingStrategies.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="AddtnlNonHispanicRaceRates.0.subRates.0.discussingStrategies.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="AddtnlNonHispanicRaceRates.0.subRates.0.discussingStrategies.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="AddtnlNonHispanicRaceRates.0.subRates.0.percentageUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="AddtnlNonHispanicRaceRates.0.subRates.0.percentageUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="AddtnlNonHispanicRaceRates.0.subRates.0.percentageUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="AddtnlNonHispanicRaceRates.0.subRates.0.percentageUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="AddtnlNonHispanicRaceRates.0.ageData1"] > .chakra-checkbox__control'
    ).click();
    cy.get(
      '[data-cy="AddtnlNonHispanicRaceRates.0.subRates.1.advisingUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="AddtnlNonHispanicRaceRates.0.subRates.1.advisingUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="AddtnlNonHispanicRaceRates.0.subRates.1.advisingUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="AddtnlNonHispanicRaceRates.0.subRates.1.advisingUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="AddtnlNonHispanicRaceRates.0.subRates.1.discussingMedications.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="AddtnlNonHispanicRaceRates.0.subRates.1.discussingMedications.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="AddtnlNonHispanicRaceRates.0.subRates.1.discussingMedications.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="AddtnlNonHispanicRaceRates.0.subRates.1.discussingMedications.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="AddtnlNonHispanicRaceRates.0.subRates.1.discussingStrategies.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="AddtnlNonHispanicRaceRates.0.subRates.1.discussingStrategies.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="AddtnlNonHispanicRaceRates.0.subRates.1.discussingStrategies.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="AddtnlNonHispanicRaceRates.0.subRates.1.discussingStrategies.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="AddtnlNonHispanicRaceRates.0.subRates.1.percentageUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="AddtnlNonHispanicRaceRates.0.subRates.1.percentageUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="AddtnlNonHispanicRaceRates.0.subRates.1.percentageUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="AddtnlNonHispanicRaceRates.0.subRates.1.percentageUsers.0.denominator"]'
    ).type("10");
    cy.get("[data-cy=CategoriesReported1] > .chakra-checkbox__control").click();

    cy.get(
      "[data-cy=EthnicityCategories0] > .chakra-checkbox__control"
    ).click();

    cy.get('[data-cy="NonHispanicEthnicityRates.ageData0"]').click();

    cy.get(
      '[data-cy="NonHispanicEthnicityRates.subRates.0.advisingUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="NonHispanicEthnicityRates.subRates.0.advisingUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="NonHispanicEthnicityRates.subRates.0.advisingUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="NonHispanicEthnicityRates.subRates.0.advisingUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="NonHispanicEthnicityRates.subRates.0.discussingMedications.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="NonHispanicEthnicityRates.subRates.0.discussingMedications.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="NonHispanicEthnicityRates.subRates.0.discussingMedications.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="NonHispanicEthnicityRates.subRates.0.discussingMedications.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="NonHispanicEthnicityRates.subRates.0.discussingStrategies.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="NonHispanicEthnicityRates.subRates.0.discussingStrategies.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="NonHispanicEthnicityRates.subRates.0.discussingStrategies.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="NonHispanicEthnicityRates.subRates.0.discussingStrategies.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="NonHispanicEthnicityRates.subRates.0.percentageUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="NonHispanicEthnicityRates.subRates.0.percentageUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="NonHispanicEthnicityRates.subRates.0.percentageUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="NonHispanicEthnicityRates.subRates.0.percentageUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="NonHispanicEthnicityRates.ageData1"] > .chakra-checkbox__control'
    ).click();

    cy.get(
      '[data-cy="NonHispanicEthnicityRates.subRates.1.advisingUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="NonHispanicEthnicityRates.subRates.1.advisingUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="NonHispanicEthnicityRates.subRates.1.advisingUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="NonHispanicEthnicityRates.subRates.1.advisingUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="NonHispanicEthnicityRates.subRates.1.discussingMedications.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="NonHispanicEthnicityRates.subRates.1.discussingMedications.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="NonHispanicEthnicityRates.subRates.1.discussingMedications.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="NonHispanicEthnicityRates.subRates.1.discussingMedications.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="NonHispanicEthnicityRates.subRates.1.discussingStrategies.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="NonHispanicEthnicityRates.subRates.1.discussingStrategies.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="NonHispanicEthnicityRates.subRates.1.discussingStrategies.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="NonHispanicEthnicityRates.subRates.1.discussingStrategies.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="NonHispanicEthnicityRates.subRates.1.percentageUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="NonHispanicEthnicityRates.subRates.1.percentageUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="NonHispanicEthnicityRates.subRates.1.percentageUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="NonHispanicEthnicityRates.subRates.1.percentageUsers.0.denominator"]'
    ).type("10");
    cy.get("[data-cy=EthnicityCategories1]").click();

    cy.get("[data-cy=HispanicIndependentReporting0]").click();
    cy.get(
      '[data-cy="HispanicEthnicityAggregateRate.ageData0"] > .chakra-checkbox__control'
    ).click();

    cy.get(
      '[data-cy="HispanicEthnicityAggregateRate.subRates.0.advisingUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="HispanicEthnicityAggregateRate.subRates.0.advisingUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="HispanicEthnicityAggregateRate.subRates.0.advisingUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="HispanicEthnicityAggregateRate.subRates.0.advisingUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="HispanicEthnicityAggregateRate.subRates.0.discussingMedications.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="HispanicEthnicityAggregateRate.subRates.0.discussingMedications.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="HispanicEthnicityAggregateRate.subRates.0.discussingMedications.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="HispanicEthnicityAggregateRate.subRates.0.discussingMedications.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="HispanicEthnicityAggregateRate.subRates.0.discussingStrategies.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="HispanicEthnicityAggregateRate.subRates.0.discussingStrategies.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="HispanicEthnicityAggregateRate.subRates.0.discussingStrategies.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="HispanicEthnicityAggregateRate.subRates.0.discussingStrategies.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="HispanicEthnicityAggregateRate.subRates.0.percentageUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="HispanicEthnicityAggregateRate.subRates.0.percentageUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="HispanicEthnicityAggregateRate.subRates.0.percentageUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="HispanicEthnicityAggregateRate.subRates.0.percentageUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="HispanicEthnicityAggregateRate.ageData1"] > .chakra-checkbox__label > .chakra-text'
    ).click();

    cy.get(
      '[data-cy="HispanicEthnicityAggregateRate.subRates.1.advisingUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="HispanicEthnicityAggregateRate.subRates.1.advisingUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="HispanicEthnicityAggregateRate.subRates.1.advisingUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="HispanicEthnicityAggregateRate.subRates.1.advisingUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="HispanicEthnicityAggregateRate.subRates.1.discussingMedications.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="HispanicEthnicityAggregateRate.subRates.1.discussingMedications.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="HispanicEthnicityAggregateRate.subRates.1.discussingMedications.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="HispanicEthnicityAggregateRate.subRates.1.discussingMedications.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="HispanicEthnicityAggregateRate.subRates.1.discussingStrategies.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="HispanicEthnicityAggregateRate.subRates.1.discussingStrategies.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="HispanicEthnicityAggregateRate.subRates.1.discussingStrategies.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="HispanicEthnicityAggregateRate.subRates.1.discussingStrategies.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="HispanicEthnicityAggregateRate.subRates.1.percentageUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="HispanicEthnicityAggregateRate.subRates.1.percentageUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="HispanicEthnicityAggregateRate.subRates.1.percentageUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="HispanicEthnicityAggregateRate.subRates.1.percentageUsers.0.denominator"]'
    ).type("10");
    cy.get("[data-cy=CategoriesReported2] > .chakra-checkbox__control").click();

    cy.get("[data-cy=SexOptions0] > .chakra-checkbox__control").click();

    cy.get(
      '[data-cy="MaleSexRates.ageData0"] > .chakra-checkbox__control'
    ).click();

    cy.get(
      '[data-cy="MaleSexRates.subRates.0.advisingUsers.0.numerator"]'
    ).click();
    cy.get(
      '[data-cy="MaleSexRates.subRates.0.advisingUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="MaleSexRates.subRates.0.advisingUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="MaleSexRates.subRates.0.advisingUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="MaleSexRates.subRates.0.advisingUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="MaleSexRates.subRates.0.discussingMedications.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="MaleSexRates.subRates.0.discussingMedications.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="MaleSexRates.subRates.0.discussingMedications.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="MaleSexRates.subRates.0.discussingMedications.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="MaleSexRates.subRates.0.discussingStrategies.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="MaleSexRates.subRates.0.discussingStrategies.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="MaleSexRates.subRates.0.discussingStrategies.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="MaleSexRates.subRates.0.discussingStrategies.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="MaleSexRates.subRates.0.percentageUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="MaleSexRates.subRates.0.percentageUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="MaleSexRates.subRates.0.percentageUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="MaleSexRates.subRates.0.percentageUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="MaleSexRates.ageData1"] > .chakra-checkbox__control'
    ).click();

    cy.get(
      '[data-cy="MaleSexRates.subRates.1.advisingUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="MaleSexRates.subRates.1.advisingUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="MaleSexRates.subRates.1.advisingUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="MaleSexRates.subRates.1.advisingUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="MaleSexRates.subRates.1.discussingMedications.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="MaleSexRates.subRates.1.discussingMedications.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="MaleSexRates.subRates.1.discussingMedications.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="MaleSexRates.subRates.1.discussingMedications.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="MaleSexRates.subRates.1.discussingStrategies.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="MaleSexRates.subRates.1.discussingStrategies.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="MaleSexRates.subRates.1.discussingStrategies.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="MaleSexRates.subRates.1.discussingStrategies.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="MaleSexRates.subRates.1.percentageUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="MaleSexRates.subRates.1.percentageUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="MaleSexRates.subRates.1.percentageUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="MaleSexRates.subRates.1.percentageUsers.0.denominator"]'
    ).type("10");
    cy.get("[data-cy=SexOptions1] > .chakra-checkbox__control").click();

    cy.get(
      '[data-cy="FemaleSexRates.ageData0"] > .chakra-checkbox__control'
    ).click();

    cy.get(
      '[data-cy="FemaleSexRates.subRates.0.advisingUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="FemaleSexRates.subRates.0.advisingUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="FemaleSexRates.subRates.0.advisingUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="FemaleSexRates.subRates.0.advisingUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="FemaleSexRates.subRates.0.discussingMedications.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="FemaleSexRates.subRates.0.discussingMedications.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="FemaleSexRates.subRates.0.discussingMedications.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="FemaleSexRates.subRates.0.discussingMedications.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="FemaleSexRates.subRates.0.discussingStrategies.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="FemaleSexRates.subRates.0.discussingStrategies.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="FemaleSexRates.subRates.0.discussingStrategies.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="FemaleSexRates.subRates.0.discussingStrategies.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="FemaleSexRates.subRates.0.percentageUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="FemaleSexRates.subRates.0.percentageUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="FemaleSexRates.subRates.0.percentageUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="FemaleSexRates.subRates.0.percentageUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="FemaleSexRates.ageData1"] > .chakra-checkbox__control'
    ).click();

    cy.get(
      '[data-cy="FemaleSexRates.subRates.1.advisingUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="FemaleSexRates.subRates.1.advisingUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="FemaleSexRates.subRates.1.advisingUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="FemaleSexRates.subRates.1.advisingUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="FemaleSexRates.subRates.1.discussingMedications.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="FemaleSexRates.subRates.1.discussingMedications.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="FemaleSexRates.subRates.1.discussingMedications.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="FemaleSexRates.subRates.1.discussingMedications.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="FemaleSexRates.subRates.1.discussingStrategies.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="FemaleSexRates.subRates.1.discussingStrategies.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="FemaleSexRates.subRates.1.discussingStrategies.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="FemaleSexRates.subRates.1.discussingStrategies.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="FemaleSexRates.subRates.1.percentageUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="FemaleSexRates.subRates.1.percentageUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="FemaleSexRates.subRates.1.percentageUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="FemaleSexRates.subRates.1.percentageUsers.0.denominator"]'
    ).type("10");
    cy.get("[data-cy=CategoriesReported3] > .chakra-checkbox__control").click();

    cy.get("[data-cy=PrimaryLanguageOptions0]").click();

    cy.get(
      '[data-cy="EnglishLanguageRate.ageData0"] > .chakra-checkbox__control'
    ).click();

    cy.get(
      '[data-cy="EnglishLanguageRate.subRates.0.advisingUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="EnglishLanguageRate.subRates.0.advisingUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="EnglishLanguageRate.subRates.0.advisingUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="EnglishLanguageRate.subRates.0.advisingUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="EnglishLanguageRate.subRates.0.discussingMedications.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="EnglishLanguageRate.subRates.0.discussingMedications.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="EnglishLanguageRate.subRates.0.discussingMedications.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="EnglishLanguageRate.subRates.0.discussingMedications.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="EnglishLanguageRate.subRates.0.discussingStrategies.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="EnglishLanguageRate.subRates.0.discussingStrategies.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="EnglishLanguageRate.subRates.0.discussingStrategies.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="EnglishLanguageRate.subRates.0.discussingStrategies.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="EnglishLanguageRate.subRates.0.percentageUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="EnglishLanguageRate.subRates.0.percentageUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="EnglishLanguageRate.subRates.0.percentageUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="EnglishLanguageRate.subRates.0.percentageUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="EnglishLanguageRate.ageData1"] > .chakra-checkbox__control'
    ).click();

    cy.get(
      '[data-cy="EnglishLanguageRate.subRates.1.advisingUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="EnglishLanguageRate.subRates.1.advisingUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="EnglishLanguageRate.subRates.1.advisingUsers.0.denominator"]'
    ).click();
    cy.get(
      '[data-cy="EnglishLanguageRate.subRates.1.advisingUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="EnglishLanguageRate.subRates.1.advisingUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="EnglishLanguageRate.subRates.1.discussingMedications.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="EnglishLanguageRate.subRates.1.discussingMedications.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="EnglishLanguageRate.subRates.1.discussingMedications.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="EnglishLanguageRate.subRates.1.discussingMedications.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="EnglishLanguageRate.subRates.1.discussingStrategies.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="EnglishLanguageRate.subRates.1.discussingStrategies.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="EnglishLanguageRate.subRates.1.discussingStrategies.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="EnglishLanguageRate.subRates.1.discussingStrategies.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="EnglishLanguageRate.subRates.1.percentageUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="EnglishLanguageRate.subRates.1.percentageUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="EnglishLanguageRate.subRates.1.percentageUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="EnglishLanguageRate.subRates.1.percentageUsers.0.denominator"]'
    ).type("10");
    cy.get(
      "[data-cy=PrimaryLanguageOptions1] > .chakra-checkbox__control"
    ).click();

    cy.get(
      '[data-cy="SpanishLanguageRate.ageData0"] > .chakra-checkbox__control'
    ).click();

    cy.get(
      '[data-cy="SpanishLanguageRate.subRates.0.advisingUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="SpanishLanguageRate.subRates.0.advisingUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="SpanishLanguageRate.subRates.0.advisingUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="SpanishLanguageRate.subRates.0.advisingUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="SpanishLanguageRate.subRates.0.discussingMedications.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="SpanishLanguageRate.subRates.0.discussingMedications.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="SpanishLanguageRate.subRates.0.discussingMedications.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="SpanishLanguageRate.subRates.0.discussingMedications.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="SpanishLanguageRate.subRates.0.discussingStrategies.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="SpanishLanguageRate.subRates.0.discussingStrategies.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="SpanishLanguageRate.subRates.0.discussingStrategies.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="SpanishLanguageRate.subRates.0.discussingStrategies.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="SpanishLanguageRate.subRates.0.percentageUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="SpanishLanguageRate.subRates.0.percentageUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="SpanishLanguageRate.subRates.0.percentageUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="SpanishLanguageRate.subRates.0.percentageUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="SpanishLanguageRate.ageData1"] > .chakra-checkbox__control'
    ).click();

    cy.get(
      '[data-cy="SpanishLanguageRate.subRates.1.advisingUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="SpanishLanguageRate.subRates.1.advisingUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="SpanishLanguageRate.subRates.1.advisingUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="SpanishLanguageRate.subRates.1.advisingUsers.0.denominator"]'
    ).type("10");
    cy.get(
      ":nth-child(4) > :nth-child(2) > :nth-child(1) > :nth-child(1) > :nth-child(1) > :nth-child(2) > :nth-child(2) > :nth-child(1) > .css-0 > :nth-child(1) > .css-n21gh5 > :nth-child(2) > .chakra-collapse > .css-zhlq69"
    ).click();
    cy.get(
      '[data-cy="SpanishLanguageRate.subRates.1.discussingMedications.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="SpanishLanguageRate.subRates.1.discussingMedications.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="SpanishLanguageRate.subRates.1.discussingMedications.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="SpanishLanguageRate.subRates.1.discussingMedications.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="SpanishLanguageRate.subRates.1.discussingStrategies.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="SpanishLanguageRate.subRates.1.discussingStrategies.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="SpanishLanguageRate.subRates.1.discussingStrategies.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="SpanishLanguageRate.subRates.1.discussingStrategies.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="SpanishLanguageRate.subRates.1.percentageUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="SpanishLanguageRate.subRates.1.percentageUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="SpanishLanguageRate.subRates.1.percentageUsers.0.denominator"]'
    ).click();
    cy.get(
      '[data-cy="SpanishLanguageRate.subRates.1.percentageUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="SpanishLanguageRate.subRates.1.percentageUsers.0.denominator"]'
    ).type("10");
    cy.get("[data-cy=CategoriesReported4] > .chakra-checkbox__control").click();

    cy.get(
      "[data-cy=DisabilityStatusOptions0] > .chakra-checkbox__control"
    ).click();

    cy.get(
      '[data-cy="DisabilitySSIRate.ageData0"] > .chakra-checkbox__control'
    ).click();

    cy.get(
      '[data-cy="DisabilitySSIRate.subRates.0.advisingUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="DisabilitySSIRate.subRates.0.advisingUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="DisabilitySSIRate.subRates.0.advisingUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="DisabilitySSIRate.subRates.0.advisingUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="DisabilitySSIRate.subRates.0.discussingMedications.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="DisabilitySSIRate.subRates.0.discussingMedications.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="DisabilitySSIRate.subRates.0.discussingMedications.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="DisabilitySSIRate.subRates.0.discussingMedications.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="DisabilitySSIRate.subRates.0.discussingStrategies.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="DisabilitySSIRate.subRates.0.discussingStrategies.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="DisabilitySSIRate.subRates.0.discussingStrategies.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="DisabilitySSIRate.subRates.0.discussingStrategies.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="DisabilitySSIRate.subRates.0.percentageUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="DisabilitySSIRate.subRates.0.percentageUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="DisabilitySSIRate.subRates.0.percentageUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="DisabilitySSIRate.subRates.0.percentageUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="DisabilitySSIRate.ageData1"] > .chakra-checkbox__control'
    ).click();

    cy.get(
      '[data-cy="DisabilitySSIRate.subRates.1.advisingUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="DisabilitySSIRate.subRates.1.advisingUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="DisabilitySSIRate.subRates.1.advisingUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="DisabilitySSIRate.subRates.1.advisingUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="DisabilitySSIRate.subRates.1.discussingMedications.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="DisabilitySSIRate.subRates.1.discussingMedications.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="DisabilitySSIRate.subRates.1.discussingMedications.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="DisabilitySSIRate.subRates.1.discussingMedications.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="DisabilitySSIRate.subRates.1.discussingStrategies.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="DisabilitySSIRate.subRates.1.discussingStrategies.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="DisabilitySSIRate.subRates.1.discussingStrategies.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="DisabilitySSIRate.subRates.1.discussingStrategies.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="DisabilitySSIRate.subRates.1.percentageUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="DisabilitySSIRate.subRates.1.percentageUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="DisabilitySSIRate.subRates.1.percentageUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="DisabilitySSIRate.subRates.1.percentageUsers.0.denominator"]'
    ).type("10");
    cy.get(
      "[data-cy=DisabilityStatusOptions1] > .chakra-checkbox__control"
    ).click();

    cy.get(
      '[data-cy="DisabilityNonSSIRate.ageData0"] > .chakra-checkbox__control'
    ).click();

    cy.get(
      '[data-cy="DisabilityNonSSIRate.subRates.0.advisingUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="DisabilityNonSSIRate.subRates.0.advisingUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="DisabilityNonSSIRate.subRates.0.advisingUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="DisabilityNonSSIRate.subRates.0.advisingUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="DisabilityNonSSIRate.subRates.0.discussingMedications.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="DisabilityNonSSIRate.subRates.0.discussingMedications.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="DisabilityNonSSIRate.subRates.0.discussingMedications.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="DisabilityNonSSIRate.subRates.0.discussingMedications.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="DisabilityNonSSIRate.subRates.0.discussingStrategies.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="DisabilityNonSSIRate.subRates.0.discussingStrategies.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="DisabilityNonSSIRate.subRates.0.discussingStrategies.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="DisabilityNonSSIRate.subRates.0.discussingStrategies.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="DisabilityNonSSIRate.subRates.0.percentageUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="DisabilityNonSSIRate.subRates.0.percentageUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="DisabilityNonSSIRate.subRates.0.percentageUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="DisabilityNonSSIRate.subRates.0.percentageUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="DisabilityNonSSIRate.ageData1"] > .chakra-checkbox__control'
    ).click();

    cy.get(
      '[data-cy="DisabilityNonSSIRate.subRates.1.advisingUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="DisabilityNonSSIRate.subRates.1.advisingUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="DisabilityNonSSIRate.subRates.1.advisingUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="DisabilityNonSSIRate.subRates.1.advisingUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="DisabilityNonSSIRate.subRates.1.discussingMedications.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="DisabilityNonSSIRate.subRates.1.discussingMedications.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="DisabilityNonSSIRate.subRates.1.discussingMedications.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="DisabilityNonSSIRate.subRates.1.discussingMedications.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="DisabilityNonSSIRate.subRates.1.discussingStrategies.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="DisabilityNonSSIRate.subRates.1.discussingStrategies.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="DisabilityNonSSIRate.subRates.1.discussingStrategies.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="DisabilityNonSSIRate.subRates.1.discussingStrategies.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="DisabilityNonSSIRate.subRates.1.percentageUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="DisabilityNonSSIRate.subRates.1.percentageUsers.0.numerator"]'
    ).type("1");
    cy.get(
      ":nth-child(5) > :nth-child(2) > :nth-child(1) > :nth-child(1) > :nth-child(1) > :nth-child(2) > :nth-child(2) > :nth-child(1) > .css-0 > :nth-child(1) > .css-n21gh5 > :nth-child(2) > .chakra-collapse > .css-zhlq69"
    ).click();
    cy.get(
      '[data-cy="DisabilityNonSSIRate.subRates.1.percentageUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="DisabilityNonSSIRate.subRates.1.percentageUsers.0.denominator"]'
    ).type("10");
    cy.get("[data-cy=CategoriesReported5] > .chakra-checkbox__control").click();

    cy.get("[data-cy=GeographyOptions0]").click();

    cy.get(
      '[data-cy="UrbanGeographyRate.ageData0"] > .chakra-checkbox__control'
    ).click();

    cy.get(
      '[data-cy="UrbanGeographyRate.subRates.0.advisingUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="UrbanGeographyRate.subRates.0.advisingUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="UrbanGeographyRate.subRates.0.advisingUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="UrbanGeographyRate.subRates.0.advisingUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="UrbanGeographyRate.subRates.0.discussingMedications.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="UrbanGeographyRate.subRates.0.discussingMedications.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="UrbanGeographyRate.subRates.0.discussingMedications.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="UrbanGeographyRate.subRates.0.discussingMedications.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="UrbanGeographyRate.subRates.0.discussingStrategies.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="UrbanGeographyRate.subRates.0.discussingStrategies.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="UrbanGeographyRate.subRates.0.discussingStrategies.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="UrbanGeographyRate.subRates.0.discussingStrategies.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="UrbanGeographyRate.subRates.0.percentageUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="UrbanGeographyRate.subRates.0.percentageUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="UrbanGeographyRate.subRates.0.percentageUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="UrbanGeographyRate.subRates.0.percentageUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="UrbanGeographyRate.ageData1"] > .chakra-checkbox__control'
    ).click();

    cy.get(
      '[data-cy="UrbanGeographyRate.subRates.1.advisingUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="UrbanGeographyRate.subRates.1.advisingUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="UrbanGeographyRate.subRates.1.advisingUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="UrbanGeographyRate.subRates.1.advisingUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="UrbanGeographyRate.subRates.1.discussingMedications.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="UrbanGeographyRate.subRates.1.discussingMedications.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="UrbanGeographyRate.subRates.1.discussingMedications.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="UrbanGeographyRate.subRates.1.discussingMedications.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="UrbanGeographyRate.subRates.1.discussingStrategies.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="UrbanGeographyRate.subRates.1.discussingStrategies.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="UrbanGeographyRate.subRates.1.discussingStrategies.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="UrbanGeographyRate.subRates.1.discussingStrategies.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="UrbanGeographyRate.subRates.1.percentageUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="UrbanGeographyRate.subRates.1.percentageUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="UrbanGeographyRate.subRates.1.percentageUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="UrbanGeographyRate.subRates.1.percentageUsers.0.denominator"]'
    ).type("10");
    cy.get("[data-cy=GeographyOptions1]").click();

    cy.get(
      '[data-cy="RuralGeographyRate.ageData0"] > .chakra-checkbox__control'
    ).click();

    cy.get(
      '[data-cy="RuralGeographyRate.subRates.0.advisingUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="RuralGeographyRate.subRates.0.advisingUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="RuralGeographyRate.subRates.0.advisingUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="RuralGeographyRate.subRates.0.advisingUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="RuralGeographyRate.subRates.0.discussingMedications.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="RuralGeographyRate.subRates.0.discussingMedications.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="RuralGeographyRate.subRates.0.discussingMedications.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="RuralGeographyRate.subRates.0.discussingMedications.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="RuralGeographyRate.subRates.0.discussingStrategies.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="RuralGeographyRate.subRates.0.discussingStrategies.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="RuralGeographyRate.subRates.0.discussingStrategies.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="RuralGeographyRate.subRates.0.discussingStrategies.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="RuralGeographyRate.subRates.0.percentageUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="RuralGeographyRate.subRates.0.percentageUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="RuralGeographyRate.subRates.0.percentageUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="RuralGeographyRate.subRates.0.percentageUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="RuralGeographyRate.ageData1"] > .chakra-checkbox__control'
    ).click();

    cy.get(
      '[data-cy="RuralGeographyRate.subRates.1.advisingUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="RuralGeographyRate.subRates.1.advisingUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="RuralGeographyRate.subRates.1.advisingUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="RuralGeographyRate.subRates.1.advisingUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="RuralGeographyRate.subRates.1.discussingMedications.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="RuralGeographyRate.subRates.1.discussingMedications.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="RuralGeographyRate.subRates.1.discussingMedications.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="RuralGeographyRate.subRates.1.discussingMedications.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="RuralGeographyRate.subRates.1.discussingStrategies.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="RuralGeographyRate.subRates.1.discussingStrategies.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="RuralGeographyRate.subRates.1.discussingStrategies.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="RuralGeographyRate.subRates.1.discussingStrategies.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="RuralGeographyRate.subRates.1.percentageUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="RuralGeographyRate.subRates.1.percentageUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="RuralGeographyRate.subRates.1.percentageUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="RuralGeographyRate.subRates.1.percentageUsers.0.denominator"]'
    ).type("10");
    cy.get("[data-cy=CategoriesReported6] > .chakra-checkbox__control").click();

    cy.get(
      '[data-cy="ACAGroupRate.ageData0"] > .chakra-checkbox__control'
    ).click();

    cy.get(
      '[data-cy="ACAGroupRate.subRates.0.advisingUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="ACAGroupRate.subRates.0.advisingUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="ACAGroupRate.subRates.0.advisingUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="ACAGroupRate.subRates.0.advisingUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="ACAGroupRate.subRates.0.discussingMedications.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="ACAGroupRate.subRates.0.discussingMedications.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="ACAGroupRate.subRates.0.discussingMedications.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="ACAGroupRate.subRates.0.discussingMedications.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="ACAGroupRate.subRates.0.discussingStrategies.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="ACAGroupRate.subRates.0.discussingStrategies.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="ACAGroupRate.subRates.0.discussingStrategies.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="ACAGroupRate.subRates.0.discussingStrategies.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="ACAGroupRate.subRates.0.percentageUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="ACAGroupRate.subRates.0.percentageUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="ACAGroupRate.subRates.0.percentageUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="ACAGroupRate.subRates.0.percentageUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="ACAGroupRate.ageData1"] > .chakra-checkbox__control'
    ).click();

    cy.get(
      '[data-cy="ACAGroupRate.subRates.1.advisingUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="ACAGroupRate.subRates.1.advisingUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="ACAGroupRate.subRates.1.advisingUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="ACAGroupRate.subRates.1.advisingUsers.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="ACAGroupRate.subRates.1.discussingMedications.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="ACAGroupRate.subRates.1.discussingMedications.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="ACAGroupRate.subRates.1.discussingMedications.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="ACAGroupRate.subRates.1.discussingMedications.0.denominator"]'
    ).type("10");
    cy.get(
      '[data-cy="ACAGroupRate.subRates.1.discussingStrategies.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="ACAGroupRate.subRates.1.discussingStrategies.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="ACAGroupRate.subRates.1.discussingStrategies.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="ACAGroupRate.subRates.1.discussingStrategies.0.denominator"]'
    ).type("10");
    cy.get(
      ":nth-child(7) > :nth-child(2) > :nth-child(1) > .css-0 > :nth-child(1) > .css-n21gh5 > :nth-child(2) > .chakra-collapse > .css-zhlq69 > :nth-child(5) > .chakra-stack > :nth-child(1)"
    ).click();
    cy.get(
      '[data-cy="ACAGroupRate.subRates.1.percentageUsers.0.numerator"]'
    ).clear();
    cy.get(
      '[data-cy="ACAGroupRate.subRates.1.percentageUsers.0.numerator"]'
    ).type("1");
    cy.get(
      '[data-cy="ACAGroupRate.subRates.1.percentageUsers.0.denominator"]'
    ).clear();
    cy.get(
      '[data-cy="ACAGroupRate.subRates.1.percentageUsers.0.denominator"]'
    ).type("10");
    cy.get("[data-cy=AdditionalNotes-AdditionalNotes]").click();
    cy.get("[data-cy=AdditionalNotes-AdditionalNotes]").click();
  });

  /* ==== Test Created with Cypress Studio ==== */
  it("File upload and button verification", function () {
    const filePath = "/files/";
    cy.xpath("//u[contains(text(),'browse')]").scrollIntoView();
    const browseBTN = "//u[contains(text(),'browse')]";
    cy.xpath(browseBTN).attachFile(filePath + "test3.docx", {
      subjectType: "drag-n-drop",
    });
    cy.get(".css-9uu7yb > .chakra-text").should("be.visible");
    cy.get('[data-cy="Validate Measure"]').should("be.visible");
    cy.get('[data-cy="Complete Measure"]').should("be.visible");
    cy.get("[data-cy=Save]").should("be.visible");
    cy.get('[href="/WY/2021/ACS/MSC-AD"]').should("be.visible");
  });
});
