export const DataSourceData = {
  default: {
    DataSourceSelections: {
      AdministrativeData0: {
        selected: [
          "AdministrativeDataOther",
          "MedicaidManagementInformationSystemMMIS",
        ],
      },
      OtherDataSource: {
        description: "dun dun dun",
      },
      "AdministrativeData0-AdministrativeDataOther": {
        description: "Another one bites the dust",
      },
    },
    DataSourceDescription: "Another one bites the dust",
    DataSource: ["AdministrativeData", "OtherDataSource"],
  },
  custom: {
    DataSourceSelections: {
      Option10: {
        selected: ["Imnottelling", "Youllhavetokillmefirst"],
      },
      "Option10-Youllhavetokillmefirst": {
        description: "Another one bites the dust",
      },
      ABetterOption: {
        description: "dun dun dun",
      },
    },
    DataSourceDescription: "Another one bites the dust",
    DataSource: [
      "Option1",
      "ABetterOption",
      "SomethingEvenCrazierThanTheFirst2",
    ],
  },
};

export const DefinitionOfPopulationData = {
  adult: {
    "DenominatorDefineTotalTechSpec-No-Explanation":
      "Another one bites the dust",
    "DeliverySys-Other-Percent": "12",
    "DeliverySys-PrimaryCareManagement-No-Percent": "12",
    DeliverySysRepresentationDenominator: [
      "FFS",
      "PCCM",
      "MCO-PIHP",
      "ICM",
      "Other",
    ],
    DefinitionOfDenominator: [
      "DenominatorIncMedicaidPop",
      "DenominatorIncCHIP",
      "DenominatorIncMedicareMedicaidDualEligible",
      "DenominatorIncOther",
    ],
    "DenominatorDefineTotalTechSpec-No-Size": "1234567890",
    "DeliverySys-MCO_PIHP-No-Excluded": "1234567890",
    "DeliverySys-IntegratedCareModel-No-Population": "1234567890",
    ChangeInPopulationExplanation: "dun dun dun",
    "DeliverySys-MCO_PIHP-NumberOfPlans": "1234567890",
    "DeliverySys-FeeForService-No-Percent": "12",
    "DeliverySys-IntegratedCareModel": "no",
    "DeliverySys-Other-NumberOfHealthPlans": "1234567890",
    "DefinitionOfDenominator-Other": "Another one bites the dust",
    DenominatorDefineTotalTechSpec: "no",
    "DeliverySys-MCO_PIHP": "no",
    "DeliverySys-MCO_PIHP-No-Included": "12",
    "DeliverySys-PrimaryCareManagement": "no",
    "DeliverySys-IntegratedCareModel-No-Percent": "12",
    "DeliverySys-Other": "Another one bites the dust",
    "DeliverySys-FeeForService": "no",
  },

  adultHybrid: {
    "DeliverySys-Other-Percent": "12",
    "DeliverySys-PrimaryCareManagement-No-Percent": "12",
    HybridMeasurePopulationIncluded: "1234567890",
    "DenominatorDefineTotalTechSpec-No-Size": "1234567890",
    ChangeInPopulationExplanation: "dun dun dun",
    "DeliverySys-FeeForService-No-Percent": "12",
    "DeliverySys-IntegratedCareModel": "no",
    "DeliverySys-Other-NumberOfHealthPlans": "1234567890",
    DenominatorDefineTotalTechSpec: "no",
    "DeliverySys-MCO_PIHP-No-Included": "12",
    "DeliverySys-PrimaryCareManagement": "no",
    "DeliverySys-Other": "Another one bites the dust",
    "DeliverySys-FeeForService": "no",
    "DenominatorDefineTotalTechSpec-No-Explanation":
      "Another one bites the dust",
    DeliverySysRepresentationDenominator: [
      "FFS",
      "PCCM",
      "MCO-PIHP",
      "ICM",
      "Other",
    ],
    DefinitionOfDenominator: [
      "DenominatorIncMedicaidPop",
      "DenominatorIncCHIP",
      "DenominatorIncMedicareMedicaidDualEligible",
      "DenominatorIncOther",
    ],
    HybridMeasureSampleSize: "1234567890",
    "DeliverySys-MCO_PIHP-No-Excluded": "1234567890",
    "DeliverySys-IntegratedCareModel-No-Population": "1234567890",
    "DeliverySys-MCO_PIHP-NumberOfPlans": "1234567890",
    "DefinitionOfDenominator-Other": "Another one bites the dust",
    "DeliverySys-MCO_PIHP": "no",
    "DeliverySys-IntegratedCareModel-No-Percent": "12",
  },

  child: {
    "DenominatorDefineTotalTechSpec-No-Explanation":
      "Another one bites the dust",
    "DeliverySys-Other-Percent": "12",
    "DeliverySys-PrimaryCareManagement-No-Percent": "12",
    DeliverySysRepresentationDenominator: [
      "FFS",
      "PCCM",
      "MCO-PIHP",
      "ICM",
      "Other",
    ],
    DefinitionOfDenominator: ["DenominatorIncMedicaidAndCHIPPop"],
    "DenominatorDefineTotalTechSpec-No-Size": "1234567890",
    "DeliverySys-MCO_PIHP-No-Excluded": "1234567890",
    "DeliverySys-IntegratedCareModel-No-Population": "1234567890",
    ChangeInPopulationExplanation: "Another one bites the dust",
    "DeliverySys-MCO_PIHP-NumberOfPlans": "1234567890",
    "DeliverySys-FeeForService-No-Percent": "12",
    "DeliverySys-IntegratedCareModel": "no",
    "DeliverySys-Other-NumberOfHealthPlans": "1234567890",
    DenominatorDefineTotalTechSpec: "no",
    "DeliverySys-MCO_PIHP": "no",
    "DeliverySys-MCO_PIHP-No-Included": "12",
    "DeliverySys-PrimaryCareManagement": "no",
    "DeliverySys-Other": "Another one bites the dust",
    "DeliverySys-IntegratedCareModel-No-Percent": "12",
    "DeliverySys-FeeForService": "no",
  },

  childHybrid: {
    "DenominatorDefineTotalTechSpec-No-Explanation":
      "Another one bites the dust",
    "DeliverySys-Other-Percent": "12",
    "DeliverySys-PrimaryCareManagement-No-Percent": "12",
    HybridMeasurePopulationIncluded: "1234567890",
    DeliverySysRepresentationDenominator: [
      "FFS",
      "PCCM",
      "MCO-PIHP",
      "ICM",
      "Other",
    ],
    DefinitionOfDenominator: ["DenominatorIncMedicaidAndCHIPPop"],
    "DenominatorDefineTotalTechSpec-No-Size": "1234567890",
    HybridMeasureSampleSize: "1234567890",
    "DeliverySys-MCO_PIHP-No-Excluded": "1234567890",
    "DeliverySys-IntegratedCareModel-No-Population": "1234567890",
    ChangeInPopulationExplanation: "Another one bites the dust",
    "DeliverySys-MCO_PIHP-NumberOfPlans": "1234567890",
    "DeliverySys-FeeForService-No-Percent": "12",
    "DeliverySys-IntegratedCareModel": "no",
    "DeliverySys-Other-NumberOfHealthPlans": "1234567890",
    DenominatorDefineTotalTechSpec: "no",
    "DeliverySys-MCO_PIHP": "no",
    "DeliverySys-MCO_PIHP-No-Included": "12",
    "DeliverySys-PrimaryCareManagement": "no",
    "DeliverySys-IntegratedCareModel-No-Percent": "12",
    "DeliverySys-Other": "Another one bites the dust",
    "DeliverySys-FeeForService": "no",
  },

  healthHome: {
    "DeliverySys-Other-Percent": "12",
    "DeliverySys-PrimaryCareManagement-No-Percent": "12",
    "DenominatorDefineTotalTechSpec-No-Size": "1234567890",
    ChangeInPopulationExplanation: "dun dun dun",
    "DeliverySys-FeeForService-No-Percent": "12",
    "DeliverySys-IntegratedCareModel": "no",
    "DeliverySys-Other-NumberOfHealthPlans": "1234567890",
    DenominatorDefineTotalTechSpec: "no",
    "DeliverySys-MCO_PIHP-No-Included": "12",
    "DeliverySys-PrimaryCareManagement": "no",
    "DeliverySys-Other": "Another one bites the dust",
    "DeliverySys-FeeForService": "no",
    "DenominatorDefineTotalTechSpec-No-Explanation":
      "Another one bites the dust",
    DeliverySysRepresentationDenominator: [
      "FFS",
      "PCCM",
      "MCO-PIHP",
      "ICM",
      "Other",
    ],
    DefinitionOfDenominator: [
      "DenominatorIncMedicaidPop",
      "DenominatorIncMedicareMedicaidDualEligible",
      "DenominatorIncOther",
    ],
    DenominatorDefineHealthHome: "no",
    "DeliverySys-MCO_PIHP-No-Excluded": "1234567890",
    "DeliverySys-IntegratedCareModel-No-Population": "1234567890",
    "DeliverySys-MCO_PIHP-NumberOfPlans": "1234567890",
    "DefinitionOfDenominator-Other": "Another one bites the dust",
    "DeliverySys-MCO_PIHP": "no",
    "DeliverySys-IntegratedCareModel-No-Percent": "12",
    "DenominatorDefineHealthHome-No-Explanation": "Another one bites the dust",
  },

  healthHomeHybrid: {
    "DeliverySys-Other-Percent": "12",
    "DeliverySys-PrimaryCareManagement-No-Percent": "12",
    HybridMeasurePopulationIncluded: "1234567890",
    "DenominatorDefineTotalTechSpec-No-Size": "1234567890",
    ChangeInPopulationExplanation: "dun dun dun",
    "DeliverySys-FeeForService-No-Percent": "12",
    "DeliverySys-IntegratedCareModel": "no",
    "DeliverySys-Other-NumberOfHealthPlans": "1234567890",
    DenominatorDefineTotalTechSpec: "no",
    "DeliverySys-MCO_PIHP-No-Included": "12",
    "DeliverySys-PrimaryCareManagement": "no",
    "DeliverySys-Other": "Another one bites the dust",
    "DeliverySys-FeeForService": "no",
    "DenominatorDefineTotalTechSpec-No-Explanation":
      "Another one bites the dust",
    DeliverySysRepresentationDenominator: [
      "FFS",
      "PCCM",
      "MCO-PIHP",
      "ICM",
      "Other",
    ],
    DefinitionOfDenominator: [
      "DenominatorIncMedicaidPop",
      "DenominatorIncMedicareMedicaidDualEligible",
      "DenominatorIncOther",
    ],
    DenominatorDefineHealthHome: "no",
    HybridMeasureSampleSize: "1234567890",
    "DeliverySys-MCO_PIHP-No-Excluded": "1234567890",
    "DeliverySys-IntegratedCareModel-No-Population": "1234567890",
    "DeliverySys-MCO_PIHP-NumberOfPlans": "1234567890",
    "DefinitionOfDenominator-Other": "Another one bites the dust",
    "DeliverySys-MCO_PIHP": "no",
    "DeliverySys-IntegratedCareModel-No-Percent": "12",
    "DenominatorDefineHealthHome-No-Explanation": "Another one bites the dust",
  },
};

export const qualifierBaseData = {
  AdministrativeData: {
    numberOfAdults: "",
    minAgeOfAdults: "",
    numberOfChildren: "",
    maxAgeChildren: "",
    numberOfIndividuals: "",
    numberOfProviders: "",
  },
  CostSavingsData: {
    yearlyCostSavings: 0,
    costSavingsMethodology: "",
    costSavingsFile: [],
  },
  PercentageEnrolledInEachDeliverySystem: [{}],
  CoreSetMeasuresAuditedOrValidated: "",
  CoreSetMeasuresAuditedOrValidatedDetails: [],
  WasExternalContractorUsed: "",
  ExternalContractorsUsed: [],
  OtherContractorDetails: "",
};
