name: Pull Request

on: [pull_request]

permissions:
  id-token: write
  contents: read
  actions: read
  pull-requests: write

jobs:
  assignAuthor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Assign PR to Creator
        run: |
          if [ "$PR_AUTHOR_TYPE" != "Bot" ]
            then
              gh pr edit $PRNUM --add-assignee $PR_AUTHOR
            fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRNUM: ${{ github.event.pull_request.number }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
          PR_AUTHOR_TYPE: ${{ github.event.pull_request.user.type }}
  unit-tests:
    name: Unit Tests
    uses: ./.github/workflows/unittest-workflow.yml
    secrets:
      CODE_CLIMATE_ID: ${{ secrets.CODE_CLIMATE_ID }}
