name: Pull Request

on:
  pull_request:
    branches:
      - "master"
    types: [opened, reopened, ready_for_review, synchronize]

permissions:
  id-token: write
  contents: read
  actions: read
  pull-requests: write

jobs:
  assignAuthor:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.type != 'Bot' }}
    steps:
      - uses: actions/checkout@v4
      - name: Assign PR to Creator
        run: |
          gh pr edit $PRNUM --add-assignee $PR_AUTHOR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRNUM: ${{ github.event.pull_request.number }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
