name: Unit Tests
on:
  workflow_call:
    secrets:
      CODE_CLIMATE_ID:
        description: "Code Climate ID"
        required: false

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set variable values
        run: ./.github/build_vars.sh set_values
        env:
          CODE_CLIMATE_ID: ${{ secrets.CODE_CLIMATE_ID }}
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - uses: actions/cache@v4
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: set path
        run: |
          echo "PATH=$(pwd)/node_modules/.bin/:$PATH" >> $GITHUB_ENV
      - name: run unit tests
        run: ./test-unit.sh
      - name: publish test coverage to qlty
        uses: qltysh/qlty-action/coverage@v1
        with:
          oidc: true
          files: |
            ${{github.workspace}}/services/app-api/coverage/lcov.info
            ${{github.workspace}}/services/ui-src/coverage/lcov.info
      - name: Store unit test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: unit-test-results
          path: |
            ${{github.workspace}}/services/ui-src/coverage/lcov.info
            ${{github.workspace}}/services/app-api/coverage/lcov.info
          retention-days: 14
